### PR TITLE
include status code for Unknown Error

### PR DESCRIPTION
**Pull request by glensc**
i'm getting Unknown error. added status code to be able to diagnose this further

### CODE REVIEW

**Comment by glensc** [comment]
tail of `chef-client` run:

```
Running handlers:
[2015-01-22T14:14:59+02:00] ERROR: Running exception handlers
  - SyslogReporting
Running handlers complete
[2015-01-22T14:14:59+02:00] ERROR: Exception handlers complete
[2015-01-22T14:14:59+02:00] FATAL: Stacktrace dumped to /var/cache/chef/chef-stacktrace.out
[2015-01-22T14:14:59+02:00] DEBUG: FFI_Yajl::EncodeError: Unknown YAJL Error (7), please report this as a bug
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:50:in `raise_error_for_status'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `ffi_yajl'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `ffi_yajl'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `ffi_yajl'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `ffi_yajl'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `ffi_yajl'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `ffi_yajl'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `do_yajl_encode'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:21:in `encode'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/encoder.rb:27:in `encode'
/usr/share/ruby/vendor_ruby/1.9/ffi_yajl/json_gem.rb:66:in `to_json'
/usr/share/ruby/vendor_ruby/chef/json_compat.rb:91:in `to_json'
/usr/share/ruby/vendor_ruby/chef/http/json_input.rb:34:in `handle_request'
/usr/share/ruby/vendor_ruby/chef/http.rb:222:in `block in apply_request_middleware'
/usr/share/ruby/vendor_ruby/chef/http.rb:220:in `each'
/usr/share/ruby/vendor_ruby/chef/http.rb:220:in `inject'
/usr/share/ruby/vendor_ruby/chef/http.rb:220:in `apply_request_middleware'
/usr/share/ruby/vendor_ruby/chef/http.rb:141:in `request'
/usr/share/ruby/vendor_ruby/chef/http.rb:118:in `put'
/usr/share/ruby/vendor_ruby/chef/node.rb:524:in `save'
/usr/share/ruby/vendor_ruby/chef/client.rb:287:in `save_updated_node'
/usr/share/ruby/vendor_ruby/chef/client.rb:433:in `do_run'
/usr/share/ruby/vendor_ruby/chef/client.rb:213:in `block in run'
/usr/share/ruby/vendor_ruby/chef/client.rb:207:in `fork'
/usr/share/ruby/vendor_ruby/chef/client.rb:207:in `run'
/usr/share/ruby/vendor_ruby/chef/application.rb:236:in `run_chef_client'
/usr/share/ruby/vendor_ruby/chef/application/client.rb:338:in `block in run_application'
/usr/share/ruby/vendor_ruby/chef/application/client.rb:327:in `loop'
/usr/share/ruby/vendor_ruby/chef/application/client.rb:327:in `run_application'
/usr/share/ruby/vendor_ruby/chef/application.rb:55:in `run'
/usr/bin/chef-client:26:in `<main>'
Chef Client failed. 6 resources updated in 27.581608544 seconds
[2015-01-22T14:14:59+02:00] DEBUG: Server doesn't support resource history, skipping resource report.
[2015-01-22T14:14:59+02:00] ERROR: Unknown YAJL Error (7), please report this as a bug
[2015-01-22T14:14:59+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by glensc** [comment]
the actual bug can be reproduced with this code:

```ruby
#!/usr/bin/ruby
# vim:encoding=utf-8
require 'ffi_yajl'

obj={
    "automatic"=>{
        "etc"=>{
            "passwd"=>{
                "root"=>{"dir"=>"/root", "gid"=>0, "uid"=>0, "shell"=>"/bin/sh", "gecos"=>"Elan Ruusam\xc3\xa4e"},
                "glen"=>{"dir"=>"/home/glen", "gid"=>500, "uid"=>500, "shell"=>"/bin/bash", "gecos"=>"Elan Ruusam\xE4e"},
            }
        },
    },
}

puts FFI_Yajl::Encoder.encode(obj)
```

should I open separate ticket for unable to encode invalid utf8 stream? or developers can pick it up from here?

**Comment by lamont-granquist** [comment]
yeah, i'm definitely aware of that problem.  we need a flag to sanitize the strings and replace invalid utf8 with '?' or something so that the end of chef-client runs don't fail like that.  there's an upstream bug where the source of the data should get fixed, but having chef die like that is crappy.

**Comment by glensc** [comment]
as for gecos field, it's not fixable. i mean it's not standardized what encoding /etc/passwd must be. it's just good idea to use utf-8 nowadays.

aside: i disabled "passwd" plugin (with chef-client cookbook) but somehow chef still managed to fail with this (the passwd plugin was not supposed to be ran at all). need to dig this deeper and report propertly (to ohai package or to chef package, or even chef-client cookbook)

**Comment by lamont-granquist** [comment]
Most likely you were just trying to use ohai 6 syntax to disable it which needs to be updated to ohai 7 syntax.  My thought on the bug was that the ohai passwd plugin should be sanitizing any non-utf8 strings before handing it back, because the whole rest of chef-client's internals may have issues with that kind of stuff as well in various places.

**Comment by glensc** [comment]
ah, thanks for the hint! my chef-client cookbook is rather outdated (disable not working problem is likely buried there)

**Pull request merged**
